pr: none
trigger: none

schedules:
- cron: "0 8 * * *"
  branches:
    include:
    - autogenerate
  displayName: Daily autogeneration

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true
- script: |
    set -Eeuxo pipefail
    git config user.name "Autogenerator Pipeline"
    git config user.email "azure-resource-manager-schemas@noreply.github.com"
    git checkout $(Build.SourceBranchName)
    git merge --no-commit --no-ff --strategy-option=theirs origin/master
    if ! git diff-index --quiet HEAD --; then
      git commit -m "Integrate master"
    fi
    git checkout origin/master -- schemas
  displayName: Integrate master branch
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'generator'
  displayName: 'Install packages'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'generator'
    customCommand: 'run generate-all'
  displayName: 'Generate schemas'
- script: |
    set -Eeuxo pipefail
    git config user.name "Autogenerator Pipeline"
    git config user.email "azure-resource-manager-schemas@noreply.github.com"
    git add --all schemas
    if ! git diff-index --quiet HEAD --; then
      git commit -m "Autogenerate schemas"
      git push origin $(Build.SourceBranchName)
    fi
  displayName: Commit and push changes