trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    set -Eeuxo pipefail
    cd tools
    npm install
    npm run test-ci
    cd ..
  displayName: 'Run schema tests'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: XUnit
    testResultsFiles: 'tools/test-results.xml'
    failTaskOnFailedTests: true