pr:
  branches:
    include:
    - master
trigger: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'tools'
  displayName: 'Install packages'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'tools'
    customCommand: 'run test-ci'
  displayName: 'Run schema tests'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'tools/test-results.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish test results'