trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'tools'
    customCommand: 'test-ci'
  displayName: 'Run schema tests'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: XUnit
    testResultsFiles: 'tools/test-results.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish test results'